apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-artifacts-pvc
  namespace: cube-lab
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: mlflow
  resources:
    requests:
      storage: 10Gi