apiVersion: apps/v1
kind: Deployment
metadata:
  name: gai-app
  namespace: cube-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gai-app
  template:
    metadata:
      labels:
        app: gai-app
    spec:
      containers:
        - name: gai-app
          image: <aws_account_id>.dkr.ecr.ap-northeast-1.amazonaws.com/gai-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: AZURE_OPENAI_API_KEY
              value: "{AZURE_OPENAI_API_KEY}"
            - name: AZURE_OPENAI_ENDPOINT
              value: "{AZURE_OPENAI_ENDPOINT}"
            - name: AZURE_OPENAI_API_VERSION
              value: "{AZURE_OPENAI_API_VERSION}"
            - name: AZURE_OPENAI_CHAT_DEPLOYMENT_NAME
              value: "{AZURE_OPENAI_CHAT_DEPLOYMENT_NAME}"
            - name: AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME
              value: "{AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME}"
            - name: AZURE_OPENAI_EMBEDDING_API_VERSION
              value: "{AZURE_OPENAI_EMBEDDING_API_VERSION}"
            - name: CHROMA_HOST
              value: "chromadb"
            - name: CHROMA_PORT
              value: 8000
            - name: TRACKING_SERVER_URI
              value: "http://mlflow:5000/"
            - name: DB_USER
              value: "postgres"
            - name: DB_PWD
              value: "postgres"
            - name: DB_DSN
              value: "postgres:5432/cubelab_app"

