apiVersion: apps/v1
kind: Deployment
metadata:
  name: gai-app
  namespace: cube-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gai-app
  template:
    metadata:
      labels:
        app: gai-app
    spec:
      containers:
        - name: gai-app
          image: <aws_account_id>.dkr.ecr.ap-northeast-1.amazonaws.com/gai-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: AZURE_OPENAI_API_KEY
              value: "3faafe12c7774af1922fd3df81d56653"
            - name: AZURE_OPENAI_ENDPOINT
              value: "https://cub-openai-poc-digi2.openai.azure.com/"
            - name: AZURE_OPENAI_API_VERSION
              value: "2024-05-01-preview"
            - name: AZURE_OPENAI_CHAT_DEPLOYMENT_NAME
              value: "dataeco-gpt-4o-2024-05-13"
            - name: AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME
              value: "dataeco-text-embedding-3-small"
            - name: AZURE_OPENAI_EMBEDDING_API_VERSION
              value: "2024-02-01"
            - name: CHROMA_HOST
              value: "chromadb"
            - name: TRACKING_SERVER_URI
              value: "http://mlflow:5000/"

---
apiVersion: v1
kind: Service
metadata:
  name: gai-app
  namespace: cube-lab
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: gai-app