apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromadb
  namespace: cube-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chromadb
  template:
    metadata:
      labels:
        app: chromadb
    spec:
      containers:
        - name: chromadb
          image: chromadb/chroma:0.5.5
          ports:
            - containerPort: 8000
          env:
            - name: IS_PERSISTENT
              valueFrom:
                configMapKeyRef:
                  name: chroma-config
                  key: IS_PERSISTENT
            - name: ANONYMIZED_TELEMETRY
              valueFrom:
                configMapKeyRef:
                  name: chroma-config
                  key: ANONYMIZED_TELEMETRY
          volumeMounts:
            - mountPath: /chroma/chroma
              name: chromadb-storage
      volumes:
        - name: chromadb-storage
          persistentVolumeClaim:
            claimName: chromadb-pvc