apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chromadb-pvc
  namespace: cube-lab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: flowise
  resources:
    requests:
      storage: 10Gi